export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';
export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';
export const FAV_POKEMON = 'FAV_POKEMON';
export const FAV_POKEMON_FULFILLED = 'FAV_POKEMON_FULFILLED';
export const REMOVE_POKEMON = 'REMOVE_POKEMON';
export const REMOVE_POKEMON_FULFILLED = 'REMOVE_POKEMON_FULFILLED';

export default {
  GET_POKEMONS,
  GET_POKEMONS_SUCCESS,
  GET_POKEMONS_FAILURE,
  GET_POKEMON,
  GET_POKEMON_SUCCESS,
  GET_POKEMON_FAILURE,
  FAV_POKEMON,
  FAV_POKEMON_FULFILLED,
  REMOVE_POKEMON,
  REMOVE_POKEMON_FULFILLED
};
